hardware_interface_node:
  ros__parameters:
<<<<<<< HEAD
    can_interfaces: ["can0", "can1"]
    baud_rate: 1000000

    can0:
      motor_ids: [7]
      motor_type: [06]

    can1:
      motor_ids: [1]
      motor_type: [06]
=======
    port_name: "/dev/ttyUSB0"
    baud_rate: 1000000
    motor_type: [06, 04] #, 03, 03, 04, 04, 04]
    motor_ids: [1, 2] #, 2, 3, 4, 5, 6]
>>>>>>> e02adc99855708c0aeab7727ed6ab512e364c563
